# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\x12\tmessaging\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\tMessaging\x12\x38\n\x0bSendMessage\x12\x12.messaging.Request\x1a\x13.messaging.Response\"\x00\x32P\n\x0c\x43lientNumber\x12@\n\x10SendClientNumber\x12\x12.messaging.Request\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=59
  _REQUEST._serialized_end=85
  _RESPONSE._serialized_start=87
  _RESPONSE._serialized_end=114
  _MESSAGING._serialized_start=116
  _MESSAGING._serialized_end=185
  _CLIENTNUMBER._serialized_start=187
  _CLIENTNUMBER._serialized_end=267
# @@protoc_insertion_point(module_scope)
