# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messaging.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmessaging.proto\x12\tmessaging\x1a\x1bgoogle/protobuf/empty.proto\"\x1a\n\x07Request\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x14\n\x04Term\x12\x0c\n\x04term\x18\x01 \x01(\x05\"\x1c\n\x0creceivedTerm\x12\x0c\n\x04term\x18\x01 \x01(\x05\"\x1b\n\x0bvoteGranted\x12\x0c\n\x04vote\x18\x01 \x01(\x08\"d\n\x17\x65lectionRequestResponse\x12%\n\x04term\x18\x01 \x01(\x0b\x32\x17.messaging.receivedTerm\x12\"\n\x02vg\x18\x02 \x01(\x0b\x32\x16.messaging.voteGranted2E\n\tMessaging\x12\x38\n\x0bSendMessage\x12\x12.messaging.Request\x1a\x13.messaging.Response\"\x00\x32J\n\tHeartbeat\x12=\n\rSendHeartbeat\x12\x12.messaging.Request\x1a\x16.google.protobuf.Empty\"\x00\x32P\n\x0c\x43lientNumber\x12@\n\x10SendClientNumber\x12\x12.messaging.Request\x1a\x16.google.protobuf.Empty\"\x00\x32W\n\x0bRequestVote\x12H\n\x0fSendVoteRequest\x12\x0f.messaging.Term\x1a\".messaging.electionRequestResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messaging_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=59
  _REQUEST._serialized_end=85
  _RESPONSE._serialized_start=87
  _RESPONSE._serialized_end=114
  _TERM._serialized_start=116
  _TERM._serialized_end=136
  _RECEIVEDTERM._serialized_start=138
  _RECEIVEDTERM._serialized_end=166
  _VOTEGRANTED._serialized_start=168
  _VOTEGRANTED._serialized_end=195
  _ELECTIONREQUESTRESPONSE._serialized_start=197
  _ELECTIONREQUESTRESPONSE._serialized_end=297
  _MESSAGING._serialized_start=299
  _MESSAGING._serialized_end=368
  _HEARTBEAT._serialized_start=370
  _HEARTBEAT._serialized_end=444
  _CLIENTNUMBER._serialized_start=446
  _CLIENTNUMBER._serialized_end=526
  _REQUESTVOTE._serialized_start=528
  _REQUESTVOTE._serialized_end=615
# @@protoc_insertion_point(module_scope)
